FROM oven/bun:1.3

WORKDIR /app

COPY package.json bun.lock bunfig.toml tsconfig.base.json ./
COPY packages ./packages
COPY apps ./apps

RUN bun install --frozen-lockfile
RUN bun run --filter './apps/worker' build

CMD ["bun", "apps/worker/dist/index.js"]
