FROM oven/bun:1.3

WORKDIR /app

COPY package.json bun.lock bunfig.toml tsconfig.base.json ./
COPY packages ./packages
COPY apps ./apps
COPY scripts ./scripts

RUN bun install --frozen-lockfile
RUN bun run --filter './apps/api' build

RUN chmod +x scripts/start-api.sh

EXPOSE 8088

CMD ["sh", "scripts/start-api.sh"]
